"""Add geometry and steps to routes

Revision ID: 6b2f9ac705fd
Revises: 5f23037ad170
Create Date: 2025-12-04 19:55:09.561294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2f9ac705fd'
down_revision = '5f23037ad170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('geometry', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('steps')
        batch_op.drop_column('geometry')
        batch_op.drop_column('duration_seconds')

    # ### end Alembic commands ###
